### ISSUE TITLE
Exception when a global that is used in a list is optimized out

### ISSUE THREAD

**Issue by Sei-Lisa** [Sei-Lisa/LSL-PyOptimizer#3]
Test case:

``` lsl
string a = "x";
list b = [a];

default
{
    timer()
    {
        b += "";
    }
}
```

Output:

```
Traceback (most recent call last):
  File "main.py", line 518, in <module>
    ret = main()
  File "main.py", line 501, in main
    script = script_header + outs.output(ts, options)
  File "<path redacted>/lslopt/lsloutput.py", line 441, in output
    ret += self.OutCode(node)
  File "<path redacted>/lslopt/lsloutput.py", line 385, in OutCode
    ret += ' = ' + self.OutExpr(child[0]['orig'])
  File "<path redacted>/lslopt/lsloutput.py", line 270, in OutExpr
    ret = '[' + self.OutExprList(child) + ']'
  File "<path redacted>/lslopt/lsloutput.py", line 193, in OutExprList
    ret += self.OutExpr(item)
  File "<path redacted>/lslopt/lsloutput.py", line 253, in OutExpr
    return self.FindName(expr)
  File "<path redacted>/lslopt/lsloutput.py", line 167, in FindName
    if 'scope' in node and 'NewName' in self.symtab[node['scope']][node['name']]:
KeyError: 'a'
```

The reason is that the output handler tries to output the original expression for that list element, which is kept in 'orig', when the symbol has already been deleted and removed from the symbol table.

The fix is complicated, and will probably involve getting rid of the 'orig' hack and finding a more reliable solution for using key variables inside lists in globals.

**Comment by Sei-Lisa** [comment]
Not fixed yet. Reopening.

Test case:

```lsl
integer a;
list b = [<a,0,0>];
default{timer(){
  llSetPrimitiveParams(b+b);
}}
```
